<a href="https://colab.research.google.com/github/Spanhaa/cursos_analise_dados/blob/main/analise_pandas_io.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = 'https://github.com/alura-cursos/Pandas/raw/main/superstore_data.csv'

In [3]:
dados_mercado = pd.read_csv(url)

In [5]:
dados_mercado.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

Início de Atividade:

1. Verifique se o arquivo CSV está separado por vírgula ou ponto e vírgula.
2. A codificação do arquivo é ISO-8859-1.
3. As três primeiras linhas linhas do arquivo podem ser desconsideradas, pois o cabeçalho só começa na quarta linha.
4. As 9 últimas linhas também podem ser desconsideradas, pois são apenas informações sobre onde os dados foram obtidos.
5. Para deletar as últimas linhas é necessário adicionar o parâmetro engine='python'.

In [12]:
url_atividade1 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

In [20]:
dados_atividade1 = pd.read_csv(url_atividade1,encoding='ISO-8859-1',sep=';',skiprows=3,skipfooter=9,engine='python')

Fim de atividade

Inicio da aula 2

In [21]:
url = 'https://github.com/alura-cursos/Pandas/raw/main/emissoes_CO2.xlsx?raw=True'

In [22]:
dados_co2 = pd.read_excel(url)

In [25]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [27]:
percapita = pd.read_excel(url,sheet_name='emissoes_percapita')
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
fontes = pd.read_excel(url, sheet_name='fontes')
fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [29]:
intervalo = pd.read_excel(url,sheet_name='emissoes_C02',usecols='A:D')
intervalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [30]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [31]:
dados_co2_sheets = pd.read_csv(url)
dados_co2_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'emissoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [33]:
percapita_sheets = pd.read_csv(url_percapita)
percapita_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [37]:
fontes_sheets = pd.read_csv(url_fontes)
fontes_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

Aula 3: JSON

In [38]:
dados_pacientes = pd.read_json('https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes.json')
dados_pacientes

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Nao,28.29,Sim,Nao,Nao,10,20,Nao,Feminino,65-69,Preta,Sim,Sim,Razoavel,8,Nao,Nao,Nao
996,996,Nao,25.69,Sim,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,Sim,Excelente,8,Nao,Nao,Nao
997,997,Sim,26.99,Nao,Nao,Nao,1,0,Nao,Masculino,70-74,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
998,998,Nao,44.29,Nao,Nao,Nao,30,0,Sim,Feminino,70-74,Branca,Sim,No,Boa,6,Sim,Nao,Nao
999,999,Nao,25.83,Nao,Nao,Nao,0,0,Nao,Masculino,70-74,Preta,Sim,No,Excelente,7,Nao,Nao,Nao

In [40]:
dados_pacientes_2 = pd.read_json('https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes_2.json')

In [42]:
dados_pacientes_2

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [43]:
df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])

In [44]:
df_normalizado

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [50]:
pd.json_normalize(dados_pacientes_2['Pacientes'], meta=['Pesquisa','Ano'])

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [51]:
df_normalizado.to_json('historico_pacientes_normalizado.json')

Inicio Atividade:

In [ ]:
import requests
import json

dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')
resultado = json.loads(dados_frutas.text)

dados_frutas_normalizado = pd.json_normalize(resultado)

Fim da atividade

In [2]:
import pandas as pd
import sqlalchemy

sqlalchemy.__version__

'1.4.49'

In [19]:
pip install --upgrade 'sqlalchemy<2.0'

Collecting sqlalchemy<2.0
  Downloading SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.4 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.0) (2.0.2)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.20
    Uninstalling SQLAlchemy-2.0.20:
      Successfully uninstalled SQLAlchemy-2.0.20
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.49 which is incompatible.
Successfully installed sqlalchemy-1.4.49

In [1]:
sqlalchemy.__version__

NameError: ignored

In [3]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [4]:
engine = create_engine('sqlite:///:memory:')

In [5]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)

In [6]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [7]:
dados.to_sql('clientes', engine,index=False)

438463

In [8]:
inspector = inspect(engine)

In [9]:
print(inspector.get_table_names())

['clientes']

In [10]:
query = 'select * from clientes where Categoria_de_renda = "Empregado"'

In [11]:
empregados = pd.read_sql(query, engine)

In [13]:
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [15]:
empregados.to_sql('empregados',con=engine,index=False)

226059

In [17]:
pd.read_sql_table('empregados',engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [22]:
pd.read_sql_table('empregados',engine,columns=['Grau_escolaridade'])

       Grau_escolaridade
0        Ensino superior
1        Ensino superior
2           Ensino médio
3        Ensino superior
4        Ensino superior
...                  ...
226054      Ensino médio
226055      Ensino médio
226056      Ensino médio
226057      Ensino médio
226058      Ensino médio

[226059 rows x 1 columns]